### ISSUE TITLE
Last played games on user page displayed in the wrong order

### ISSUE THREAD

**Issue by 2ion** [antzucaro/XonStat#21]
On my user page (24333), the games 450228 and 450223 are displayed in the wrong order. Reloading the page doesn't change anything (as of Tue 14 Apr 22:12:35 CEST 2015).

![2015-04-14-220941_1363x621_scrot](https://cloud.githubusercontent.com/assets/666784/7146340/26f811cc-e2f3-11e4-8039-fb2a6c20414f.png)

**Comment by antzucaro** [comment]
This is due to a server thread being busy at the time of one of the requests, delaying the creation time such that it appears "after" a game that occurred before it in time. There isn't a real fix for this, but I could switch to sorting by game_id descending instead of the game creation date.

**Comment by antzucaro** [comment]
Further information: the change to the ordering would happen here: https://github.com/antzucaro/XonStat/blob/master/xonstat/views/helpers.py#L103

**Comment by 2ion** [comment]
Thanks for the prompt reaction. This sounds like a good and trivial change to me.
